### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by SaySayTakamura** [SaySayTakamura/CWSDK#1]
This is the TODO-List, things that are planned or in-progress go here.

You can use the Suggestion thread to give me some idea on what to do, if is feasable to do so, i will put it in here.

**Comment by SaySayTakamura** [comment]
Release 2024-01:

- [ ] Document straight-forward functions
- [ ] Create function wrapper to `cube::setdaytime()`
- [ ] Create Struct Wrappers for Creature, Object and such (avoiding showing the user so much unnamed/undocumented variables)
- [ ] Update README.md
